# Generated by Django 4.0.4 on 2023-09-15 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_departamento', models.CharField(max_length=50)),
                ('nom_cargo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_documento', models.CharField(max_length=30)),
                ('Nombres', models.CharField(max_length=60)),
                ('apellido1', models.CharField(max_length=30)),
                ('apellido2', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_Registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sal_base', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sal_final', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transporte', models.CharField(max_length=10)),
                ('hora_extra', models.IntegerField()),
                ('dominicales', models.IntegerField()),
                ('diurna', models.IntegerField()),
                ('nocturnas', models.IntegerField()),
                ('recargo_nocturno', models.IntegerField()),
                ('festivos', models.IntegerField()),
                ('devengado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GestionNomina.empleado')),
            ],
        ),
    ]
